"""Initial tables

Revision ID: 4612949e1adb
Revises: 90a38b349922
Create Date: 2025-11-30 19:47:46.140319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4612949e1adb'
down_revision: Union[str, Sequence[str], None] = '90a38b349922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversations_workspace_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'workspaces', ['workspace_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('documents_workspace_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'workspaces', ['workspace_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('files_document_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('parse_jobs_document_id_fkey'), 'parse_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'parse_jobs', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('rag_documents_document_id_fkey'), 'rag_documents', type_='foreignkey')
    op.create_foreign_key(None, 'rag_documents', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rag_documents', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('rag_documents_document_id_fkey'), 'rag_documents', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'parse_jobs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('parse_jobs_document_id_fkey'), 'parse_jobs', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('files_document_id_fkey'), 'files', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'documents', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('documents_workspace_id_fkey'), 'documents', 'workspaces', ['workspace_id'], ['id'])
    op.drop_constraint(None, 'conversations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_workspace_id_fkey'), 'conversations', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###
